@MinimalAPISample_HostAddress = http://localhost:5005

### Weather Forecast
GET {{MinimalAPISample_HostAddress}}/weatherforecast/
Accept: application/json

### GET /people
GET {{MinimalAPISample_HostAddress}}/people
Accept: application/json

### GET /people/{id}
GET {{MinimalAPISample_HostAddress}}/people/2
Accept: application/json

### POST /people
POST {{MinimalAPISample_HostAddress}}/people
Content-Type: application/json

{
  "Name": "Wayki"
}

### PUT /people/{id}
PUT {{MinimalAPISample_HostAddress}}/people/2
Content-Type: application/json

{
  "Id": 2,
  "Name": "Dina Boluarte"
}

### DELETE /people/{id}
DELETE {{MinimalAPISample_HostAddress}}/people/2
Content-Type: application/json


### Message Example 
GET {{MinimalAPISample_HostAddress}}/message
Accept: application/json